### ISSUE TITLE
Lỗi - Mở form khám bệnh bị lỗi.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprescription#257]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92120`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV TMD CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbtamminhduc_cantho`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/2jyLN4N7W)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `ALL` - _**MaKB**_: `ALL` - _**MaBA**_: `ALL` _**NgayKCB**_: `ALL` - _**MaPhong**_: `ALL` - _**MaDV**_: `ALL` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi cấu hình máy có check Cấp cứu thì lúc mở form Khám bênh lên xuất hiện lỗi như hình dưới.

Check gấp dùm em vì liên quan cấp cứu BN, nên BV sẽ chậm trễ trong việc cấp cứu BN.

************** Exception Text **************
System.ArgumentException: Cannot bind to the property or column nhom_mau on the DataSource.
Parameter name: dataMember
   at System.Windows.Forms.BindToObject.CheckBinding()
   at System.Windows.Forms.Binding.SetListManager(BindingManagerBase bindingManagerBase)
   at System.Windows.Forms.ListManagerBindingsCollection.AddCore(Binding dataBinding)
   at System.Windows.Forms.BindingsCollection.Add(Binding binding)
   at System.Windows.Forms.BindingContext.UpdateBinding(BindingContext newBindingContext, Binding binding)
   at System.Windows.Forms.Binding.SetBindableComponent(IBindableComponent value)
   at System.Windows.Forms.ControlBindingsCollection.AddCore(Binding dataBinding)
   at System.Windows.Forms.BindingsCollection.Add(Binding binding)
   at System.Windows.Forms.ControlBindingsCollection.Add(String propertyName, Object dataSource, String dataMember, Boolean formattingEnabled, DataSourceUpdateMode updateMode, Object nullValue, String formatString, IFormatProvider formatInfo)
   at System.Windows.Forms.ControlBindingsCollection.Add(String propertyName, Object dataSource, String dataMember)
   at Prescription.Forms.FrmKhamBenh.bindingData()
   at Prescription.Forms.FrmKhamBenh.FrmKhamBenh_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/1e457b51-ffbc-4258-848f-5809470a3343)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Prescription.exe v.3.24.0624.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406240-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406240-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FPrescriptionexe%2F32406240-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không mở được form khám bệnh trường hợp cấu hình cấp cứu

- ☑: https://github.com/dh-hos/dhg.hospitalprescription/issues/257

- 📗: tại hàm `GetDSBenhNhanCC` lấy thêm trường `current.dmbenhnhan.nhom_mau`

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Prescription.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hospitalprescription/assets/99630883/c61dc176-5a3f-4ff2-9a85-acaa9e11be62)
